### PR TITLE
update openSUSE.asia summit in whats_hot.html

### PR DESCRIPTION
**Pull request by chenyueg**

### CODE REVIEW

**Comment by rjschwei** [comment]
I think to promote the Summit we want a web banner at the top rather then having text in the middle of the page.

I would suggest to create a web banner following what was done for oSC previously. The text should be part of news article on news.o.o

**Comment by chenyueg** [comment]
Hi Robert,

Thank you for the suggestion.

What is the scale of the banner? We can start to do it now.

Thank you.

Yue

On Wed, Jul 9, 2014 at 8:16 PM, Robert Schweikert notifications@github.com
wrote:

> I think to promote the Summit we want a web banner at the top rather then
> having text in the middle of the page.
> 
> I would suggest to create a web banner following what was done for oSC
> previously. The text should be part of news article on news.o.o
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/openSUSE/landing-page/pull/14#issuecomment-48462051.

## 

It is the time you have spent for your rose that makes your rose so
important.

**Comment by rjschwei** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

On 07/10/2014 03:22 AM, Eleanor Chen wrote:

> Hi Robert,
> 
> Thank you for the suggestion.
> 
> What is the scale of the banner? We can start to do it now.

Please check with the artteam, they have experience with this.
marketing@o.o   (opensuse.org). There will also be people willing to
help with the design.

---

Robert Schweikert                           MAY THE SOURCE BE WITH YOU
SUSE-IBM Software Integration Center                   LINUX
Tech Lead
Public Cloud Architect
rjschwei@suse.com
rschweik@ca.ibm.com
781-464-8147
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2.0.22 (GNU/Linux)
Comment: Using GnuPG with Thunderbird - http://www.enigmail.net/

iQEcBAEBAgAGBQJTvonHAAoJEE4FgL32d2UkvxoH/3FSGmCg6hlYiqycafS7ZKkl
mbwD5LAZ5g5tVhyT6XlR/zBzoGhUHnkirrpJGxC/REiBomB4zzyqrZ/vUoyvIy1s
RptZr6yjobfWf8r6u31dTH6swndWfziJfpfHWVnu9YK+lbBZ9ywu2Xd9S6WJ0Pmt
qqoVT5BiWfukXuwDQ7TWDxa2yfKaDzpjj2EvKbZnnDQYKeFVR/JAbqlQFLTCQHwi
90RcoSFczL5MM0OF2k762Sano6bRiLQlPc8Yncd34J/shpmLsv44DM+nmoDM3RHi
fgXZTSzS6hBck6TrtK9oflDZG4NW8rvaIiqALH2p+wU/z71Z8ik0cfEhE3U4s80=
=i7K9
-----END PGP SIGNATURE-----

**Comment by chenyueg** [comment]
Hi Robert,

Thank you for the advise. Would you please first merge the pull request and
then we can do a bit of advertisement earlier? The banner design will need
some time.

Thank you.

Eleanor

On Thu, Jul 10, 2014 at 8:41 PM, Robert Schweikert <notifications@github.com

> wrote:
> 
> -----BEGIN PGP SIGNED MESSAGE-----
> Hash: SHA1
> 
> On 07/10/2014 03:22 AM, Eleanor Chen wrote:
> 
> > Hi Robert,
> > 
> > Thank you for the suggestion.
> > 
> > What is the scale of the banner? We can start to do it now.
> 
> Please check with the artteam, they have experience with this.
> marketing@o.o (opensuse.org). There will also be people willing to
> help with the design.
> 
> ---
> 
> Robert Schweikert MAY THE SOURCE BE WITH YOU
> SUSE-IBM Software Integration Center LINUX
> Tech Lead
> Public Cloud Architect
> rjschwei@suse.com
> rschweik@ca.ibm.com
> 781-464-8147
> -----BEGIN PGP SIGNATURE-----
> Version: GnuPG v2.0.22 (GNU/Linux)
> Comment: Using GnuPG with Thunderbird - http://www.enigmail.net/
> 
> iQEcBAEBAgAGBQJTvonHAAoJEE4FgL32d2UkvxoH/3FSGmCg6hlYiqycafS7ZKkl
> mbwD5LAZ5g5tVhyT6XlR/zBzoGhUHnkirrpJGxC/REiBomB4zzyqrZ/vUoyvIy1s
> RptZr6yjobfWf8r6u31dTH6swndWfziJfpfHWVnu9YK+lbBZ9ywu2Xd9S6WJ0Pmt
> qqoVT5BiWfukXuwDQ7TWDxa2yfKaDzpjj2EvKbZnnDQYKeFVR/JAbqlQFLTCQHwi
> 90RcoSFczL5MM0OF2k762Sano6bRiLQlPc8Yncd34J/shpmLsv44DM+nmoDM3RHi
> fgXZTSzS6hBck6TrtK9oflDZG4NW8rvaIiqALH2p+wU/z71Z8ik0cfEhE3U4s80=
> =i7K9
> -----END PGP SIGNATURE-----
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/openSUSE/landing-page/pull/14#issuecomment-48598860.

## 

It is the time you have spent for your rose that makes your rose so
important.

**Comment by ancorgs** [comment]
No movement in this PR since July and summit already taking place. So closing.

**Pull request closed without merging**
