### PR TITLE
fix spanish translation

### PR DESCRIPTION
**Pull request by dahool**
Updated from latest svn version

### CODE REVIEW

**Comment by dahool** [comment]
The language was fixed in the second commit. I didn't notice it was changed when I merged the po with the shtml file.

**Comment by digitaltom** [comment]
Sorry for not taking care of this such a long time. 
But now it seems your pull request cannot be merged automatically anymore. 
Could you please merge with the current master?

**Comment by aplanas** [comment]
Close?

**Comment by ancorgs** [comment]
Obviously this is old stuff :-)

**Pull request closed without merging**
