### PR TITLE
Improve Spanish translation

### PR DESCRIPTION
**Pull request by javierllorente**

### CODE REVIEW

**Comment by aplanas** [comment]
:+1:

**Comment by ancorgs** [comment]
In fact, this is not the correct way to translate the page. These changes will be overwritten in the next update with the content of http://svn.opensuse.org/svn/opensuse-i18n/trunk/lcn/es/po/opensuse-org.es.po which is the "official" translation. Please contact the Spanish Localization Team http://en.opensuse.org/openSUSE:Localization_team

Gracias. :-)

**Comment by aplanas** [comment]
: ( my mistake. At least there has been a faster answer. May we need to close openSUSE/landing-page#6 too.

**Comment by javierllorente** [comment]
Oops O:-) I have also updated the translation at the right place (vertaal.tk).
Saludos

**Pull request closed without merging**
